version: '3'
services:
  postgres:
    image: infrast/pg:v1
    container_name: postgres1
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: docker_test
    restart: always
  app:
    image: infrast/spring_app:v3
    container_name: app1
    ports:
    - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docker_test
#    restart: always
    links:
      - postgres